from typing import TypedDict, Literal, Optional, Dict, List, Annotated, Field
import operator


class ComplianceIssue(TypedDict):
    category: str
    description: str
    severity: Literal["low", "medium", "high"]
    timestamp: Optional[str]


class GraphState(TypedDict):
    video_url: str
    video_id: str

    ingestion_video_path: str
    video_metadata: Dict[str, str]
    transcript: Optional[str]
    ocr_text: List[str]

    compliance_results: Annotated[List[ComplianceIssue], operator.add]

    final_result = Literal["FAIL", "PASS"]

    report: str= Field[...,"Report generated by the system in markdown format"]
    errors: Annotated[List[str], operator.add]